# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: 'Increment .csproj Version'
description: 'Increments the csproj minor or build version'
branding:
  icon: copy
  color: blue
inputs:
  version-type:
    description: 'Version type - build or minor'
    required: true
    default: 'build'
  csproj-file:
    description: 'Path to .csproj manifest'
    required: true
outputs:
  version-number:
    description: 'The new version number'
    value: ${{ steps.version_increment.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Increment csproj version
      id: version_increment
      shell: pwsh
      run: |         
          [xml]$xml = Get-Content "${{ inputs.csproj-file }}"

          $fversion = ""
          $fversionNode = ""
          $VersionNew = $false
          $test = Get-Content ${{ inputs.csproj-file }}

          if($xml.SelectSingleNode("//Project/PropertyGroup/FileVersion")) {
            $fversionNode = $xml.SelectSingleNode("//Project/PropertyGroup/FileVersion")
          }
          else {
            # Create new node for FileVersion
            $parent = $xml.SelectSingleNode("//Project/PropertyGroup")
            $newElement = $xml.CreateElement("FileVersion")
            $newElement.InnerText = "1.0.0"
            $parent.AppendChild($newElement)
            $fversionNode = $xml.SelectSingleNode("//Project/PropertyGroup/FileVersion")
            $VersionNew = $true
          }

          [Version]$fversion = $fversionNode.InnerText

          if ($versionNew -eq $false) {
            Switch("${{ version-type }}")
            {
              case "build" { $newversion = New-Object Version ([int]$fversion.Major),([int]$fversion.Minor),([int]$fversion.Build + 1) }
              case "minor" { $newversion = New-Object Version ([int]$fversion.Major),([int]$fversion.Minor + 1),([int]0) }
            }
          }

          # Set new version
          $fversionNode.InnerText = $newversion

          # Save csproj xml file
          $xml.Save("${{ inputs.csproj-file }}") | Out-Null

          Write-Output "::set-output name=version::$newversion"
